run_analysis <- function() {
  
  library("dplyr") #This invokes the library of dplyr
 
  
  activitylabels <- readactivitylabels()  #This function is reading the list of activities (6 in number) in to a dataframe
  
  featureList <- readfeatures() #This function is reading the 561 features from the feature list file in to a dataframe
 
  yData <- readY(activitylabels) #This function reads the Y train and test data and appends the activity label by merge
  
  xData <- readX(yData, featureList) #This functionread the X data (both test and train) and joins with YData and Feature List
  
  subjectData <- readsubject(xData) #This reads the subject data (both test and train) and joins with Xdata
  
  data_summary <- subjectData %>% group_by(Subject.ID, Activity.Description) %>% summarise_each(funs(mean))
  
  write.table(data_summary, file = "./final_out.txt", row.name=FALSE)
}


readactivitylabels <- function() {
  
  #This function is reading the activity labels and return the dataframe of actitvities. The function is also cleaning the data frame
  #with better description for the column names. This function is validation if the file before reading the file. 
  
  if(file.exists("./UCI HAR Dataset/activity_labels.txt")) {
   t <- read.table("./UCI HAR Dataset/activity_labels.txt")
   
   #cleaning the column names
   names(t)[1] <- "Activity.ID"
   names(t)[2] <- "Activity.Description"
   return(t) #returning the activity dataframe to the main function
  }
  else {print("Activity Label file not found")}
}

readfeatures <- function() {
  
  #This function is reading the feature description and return the dataframe of features. The function is also cleaning the data frame 
  #with better description for the column names. This function is validation if the file before reading the file. 

  
  if(file.exists("./UCI HAR Dataset/features.txt")) {
    t <- read.table("./UCI HAR Dataset/features.txt")  # t is temporary data frame
    
    #clearning the column names
    
    names(t)[1] <- "Feature.ID"
    names(t)[2] <- "Feature.Description"
    return(t) #returning the temporary datafrme to the main function()
  }
  else {print("List of features file not found")}
}

readY <- function(tdfActivityFeatures) {
  
  #This function reads both Y data (Test and Train). The Test and Train is indicated by input variable "Category
  #This function also joins (in data base sense) with Acitivity Features dataframe and merges with train/testdata
  #The tdftdfActivityFeatures is dataframe from generated by Activity Features (list) and is a input to the function
  
  
  #reading the training data
  if (file.exists("./UCI HAR Dataset/train/y_train.txt")) {
    ttraindf <- read.table("./UCI HAR Dataset/train/y_train.txt")
  } else 
  {
    print("Y Training dataset not available")
  }

  #reading the test data
  if (file.exists("./UCI HAR Dataset/test/y_test.txt")) {
    ttestdf <- read.table("./UCI HAR Dataset/test/y_test.txt")
  } else
  {
    print("Y Test dataset is not available")
  }
  

  #Using consistent and better names for the varaibles
  names(ttraindf)[1] <- "Activity.ID"
  names(ttestdf)[1] <- "Activity.ID"
  
  #creating Row ID for each row of the dataframe. RowID is important because it is used to join with all tables (subject data)
  ttraindf$RowIndex <- 1:nrow(ttraindf)
  ttestdf$RowIndex <- 1:nrow(ttestdf)
  
  #each row is marked with source of data and each source of data needs to joined with the same kind of data i.e
  #subject data of test should be joined with  test data of Y
  ttraindf$Dataset.Name <- "train"
  ttestdf$Dataset.Name <- "test"
  
  #appending the test and training data with rbind function in to new dataframe tdf
  tdf <- rbind(ttraindf,ttestdf)
  
  #Creating a composite key with RowID  and dataset Type for joining with subject data 

  tdf$Join.ID <- paste(tdf$RowIndex, tdf$Dataset.Name, sep = "-")
  
  #Joining the rwo datasets, i.e Acitvity Features and Activity Lookup
  temp <- merge(x=tdf, y = tdfActivityFeatures, by.x = "Activity.ID", by.y = "Activity.ID")
  
  #rearranging the column names to ease the ability to read the data
  temp <- select(temp, RowIndex, Dataset.Name, Join.ID, Activity.ID, Activity.Description)
  
  #sorting the dataset to preserve the all train data and test appears in sequence
  temp <- arrange(temp,Dataset.Name, RowIndex)
  
  return(temp)
}


readX <- function(tdfy, tdffeatures) {
  
  #This function reads the X data and merges with features and Y Data data.
  #This dfunction also cleans up the dataframe by selecting only the columns needed
  #The merging of the data with Y data is with combnined key of RowIndex and dataset name (Join.ID)
  
  #Reading the X Training dataset
  
  if (file.exists("./UCI HAR Dataset/train/X_train.txt")) {
    ttraindf <- read.table("./UCI HAR Dataset/train/X_train.txt")
  } else {
    print("File not found")
  }
  
  #reading the X Test data
  if (file.exists("./UCI HAR Dataset/test/X_test.txt")) {
    ttestdf <- read.table("./UCI HAR Dataset/test/X_test.txt")
  }  else {
    print("file not found")
  }
  
  #Making the unqie names out the Feature Description. 
  tempnamessvector <- make.names(tdffeatures$Feature.Description, unique=TRUE) #Makes the function names unique
  
  #Copying the unique names to the names columns of X data for both training and test 
  names(ttraindf) <-  tempnamessvector  #Copying the columns names from features dataset
  names(ttestdf) <-  tempnamessvector  #Copying the columns names from features dataset
  
  
  #copying the Row Index to each dataframe to preserve the original sequence of data and also
  #faciliate in joining the data
  ttraindf$RowIndex <- 1:nrow(ttraindf) #Adding row index to the each row of observations
  ttestdf$RowIndex <- 1:nrow(ttestdf) #Adding row index to the each row of observations
  
  #copying the source of the data - train or test dataset
  ttraindf$Dataset.Name <- "train" #Adding constant (source) to every row of training dataset#copying the source of th
  ttestdf$Dataset.Name <- "test" #Adding constant (source) to every row of training dataset
   
  #combining the data sources both test and traing
  tdf <- rbind(ttraindf,ttestdf)
  
  #selecting all columns which "mean" and "std" in the x Dataset along with RowIndex and Dataset.Name
  tdf <- select(tdf, contains("mean"), contains("std"), RowIndex, Dataset.Name)
  
  #Creating the composite key to join
  tdf$Join.ID <- paste(tdf$RowIndex, tdf$Dataset.Name, sep = "-")
  
  #joining the two dataset with Join.ID (source of data and RowID)
  temp <- merge(x=tdf, y = tdfy, by.x = "Join.ID", by.y = "Join.ID")
  
  #Removing the columns like dataset source and RowIndex
  #Rearranging the columns with Select statement 
  temp <- select(temp, Join.ID, Activity.ID, Activity.Description, contains("mean"), contains("std"))
  
  #Returning the processed data of X data
  return(temp)
}


readsubject <- function(xdatadf) {
  
  #Goal of this is to read the subject data and join with the previously built X dataset of with all columns
  #The function creates a composite key with Row Index and Source of the data to join
  
  #Reading the training subject data
  if (file.exists("./UCI HAR Dataset/train/subject_train.txt")) {
    ttraindf <- read.table("./UCI HAR Dataset/train/subject_train.txt")
  } else {
    print("Training Subject data is not present")
  }
    
  #reading the test subject data
  if (file.exists("./UCI HAR Dataset/test/subject_test.txt")) {
    ttestdf <- read.table("./UCI HAR Dataset/test/subject_test.txt")
  } else {
    print("Test Subject data is not present")
  }
  
  
  #Naming the columns names better
  names(ttraindf)[1] <- "Subject.ID"
  names(ttestdf)[1] <- "Subject.ID"
  
  #copying the Row Index to each dataframe to preserve the original sequence of data and also
  #faciliate in joining the data
  ttraindf$RowIndex <- 1:nrow(ttraindf)
  ttestdf$RowIndex <- 1:nrow(ttestdf)
  
  #copying the source of the data - train or test dataset to faciliate the joining 
  ttraindf$Dataset.Name <- "train"
  ttestdf$Dataset.Name <- "test"
  
  #merging of the training and test dataset
  tdf <- rbind(ttraindf,ttestdf)
  
  #creation of the compisite key to join the datasets
  tdf$Join.ID <- paste(tdf$RowIndex, tdf$Dataset.Name, sep = "-")
  
  #Merging (joining) Subject data with X Dataset with the composite key of Subject Data and X Data
  temp <- merge(x=tdf, y = xdatadf, by.x = "Join.ID", by.y = "Join.ID")

  temp <- select(temp, -Join.ID, -RowIndex, -Dataset.Name, -Activity.ID)
  return(temp)  
}

